### ISSUE TITLE
Introduce a delay to allow scroll on mobile

### ISSUE THREAD

**Issue by bakura10** [imgix/drift#77]
Thanks for this awesome library, looked awesome and very easy to customize!

I'm encountering a small issue though: I have an image that takes nearly all the screen estate on mobile. The zoom on mobile looks good and works well, but the issue is that I simply can't scroll at all as the touch event is immediately captured to launch the zoom.

Would it be possible to add some smarter detection so that the zoom is only started after a few milli seconds of hold? I've tried the "hoverDelay" but it does not seem to handle this use case.

Thanks :)

**Comment by frederickfogerty** [comment]
Hey there @bakura10 thanks for the suggestion!

Our development focus is currently not on Drift but we'll look at this issue when we re-focus on drift (potentially in about a month). We understand the predicament that a user is not able to scroll past a Drift element. What would you expect the interaction here to be? e.g. a long-press on Drift to activate it?

I'm not sure if a hover delay will work since we're capturing all touch events... but we'll have a look at what we can do!

- Fred, Imgix

**Comment by bakura10** [comment]
Hi !

Yes, the idea would indeed be to start enabling the zoom after a few milliseconds, to leave the opportunity to scroll :).

**Comment by elitenick** [comment]
We also would love this. Even doing drift.disable() still seems to keep it listening for the touch events, preventing scrolling.

**Comment by frederickfogerty** [comment]
Great, thanks for the comments @elitenick @bakura10 we'll see what we can do when we get back to this library.

**Comment by ITFlyer** [comment]
Let me make yet another request for this functionality. I tried to implement it myself with a combination of capturing touch events and the touch, but Drift captures all touch events, so trying to create a flag in combination with the touchDelay parameter didn't work. Also the onShow event doesn't accept a return value that would cancel the show function.

Basically I see it working like this: You touch and hold for a given amount of time (default to say 100ms) and Drift actuates. If you touch and move within that 100ms, Drift deactivates for the duration of that touch, and passes through the events to the browser, allowing it to scroll the page.
